import { Hono } from 'hono'

type Env={DB:D1Database;AUTH_MODE?:string;DEV_USER_EMAIL?:string}
type Variables={email:string;userId:string}
type Tx={tradeDate:string;transactionType:string;ticker:string;currency:string;quantity:number;price:number;amountForeign:number}

const app=new Hono<{Bindings:Env;Variables:Variables}>()
const id=()=>crypto.randomUUID()
const userKey=async(email:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(email.toLowerCase())))).map(x=>x.toString(16).padStart(2,'0')).join('')

app.use('/api/*',async(c,next)=>{const email=c.req.header('Cf-Access-Authenticated-User-Email')||(c.env.AUTH_MODE==='dev'?c.env.DEV_USER_EMAIL:undefined);if(!email)return c.json({error:'UNAUTHORIZED'},401);c.set('email',email.toLowerCase());c.set('userId',await userKey(email));await next()})

app.get('/api/health',c=>c.json({ok:true}))
app.get('/api/bootstrap',async c=>{const userId=c.get('userId');const state=await c.env.DB.prepare('SELECT cloud_revision,active_dataset_id FROM portfolio_state WHERE user_id=?').bind(userId).first<{cloud_revision:number;active_dataset_id:string|null}>();if(!state?.active_dataset_id)return c.json({revision:state?.cloud_revision??0,dataset:null});const dataset=await c.env.DB.prepare('SELECT id,filename,row_count FROM portfolio_datasets WHERE id=? AND user_id=?').bind(state.active_dataset_id,userId).first<{id:string;filename:string;row_count:number}>();const rows=await c.env.DB.prepare('SELECT trade_date,transaction_type,ticker,currency,quantity,price,amount_foreign FROM transactions WHERE dataset_id=? ORDER BY trade_date,source_row_number').bind(state.active_dataset_id).all();return c.json({revision:state.cloud_revision,dataset:dataset?{id:dataset.id,filename:dataset.filename,rowCount:dataset.row_count,transactions:rows.results.map((r:any)=>({tradeDate:r.trade_date,transactionType:r.transaction_type,ticker:r.ticker,currency:r.currency,quantity:r.quantity,price:r.price,amountForeign:r.amount_foreign}))}:null})})

app.post('/api/datasets',async c=>{const body=await c.req.json<{filename:string;baseRevision:number;transactions:Tx[]}>();if(!body.filename||!Array.isArray(body.transactions)||!body.transactions.length)return c.json({error:'INVALID_DATASET'},400);const userId=c.get('userId'),email=c.get('email');const state=await c.env.DB.prepare('SELECT cloud_revision FROM portfolio_state WHERE user_id=?').bind(userId).first<{cloud_revision:number}>();const current=state?.cloud_revision??0;if(body.baseRevision!==current)return c.json({error:'VERSION_CONFLICT',cloudRevision:current},409);const datasetId=id(),next=current+1;const statements=[c.env.DB.prepare('INSERT OR IGNORE INTO users(id,email) VALUES(?,?)').bind(userId,email),c.env.DB.prepare('INSERT OR IGNORE INTO portfolio_state(user_id,cloud_revision) VALUES(?,0)').bind(userId),c.env.DB.prepare("UPDATE portfolio_datasets SET status='ARCHIVED' WHERE user_id=? AND status='ACTIVE'").bind(userId),c.env.DB.prepare("INSERT INTO portfolio_datasets(id,user_id,revision,status,filename,file_hash,parser_version,row_count,validation_json,activated_at) VALUES(?,?,?,'ACTIVE',?,'browser','csv-v1',?,'{}',datetime('now'))").bind(datasetId,userId,next,body.filename,body.transactions.length)];body.transactions.forEach((tx,index)=>statements.push(c.env.DB.prepare('INSERT INTO transactions(id,dataset_id,user_id,source_row_number,trade_date,transaction_type,ticker,currency,quantity,price,amount_foreign,row_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(id(),datasetId,userId,index+1,tx.tradeDate,tx.transactionType,tx.ticker??'',tx.currency,tx.quantity??0,tx.price??0,tx.amountForeign??0,`${datasetId}-${index+1}`)));statements.push(c.env.DB.prepare('UPDATE portfolio_state SET active_dataset_id=?,cloud_revision=?,updated_at=datetime(\'now\') WHERE user_id=? AND cloud_revision=?').bind(datasetId,next,userId,current));const result=await c.env.DB.batch(statements);const last=result[result.length-1];if(!last.success||last.meta.changes!==1)return c.json({error:'VERSION_CONFLICT'},409);return c.json({datasetId,revision:next},201)})

export default app
